# Generated by Django 4.2.17 on 2025-04-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_delete_otpdata_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tech', models.TextField(help_text='Comma-separated tech stack (e.g., Python, React, Django)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
