# Generated by Django 4.2.17 on 2025-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='experience',
            field=models.CharField(max_length=5),
        ),
    ]
